FROM openjdk
ADD target/hangman-cmd-1.0-SNAPSHOT-jar-with-dependencies.jar hangman-cmd-1.0-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java", "-cp","hangman-cmd-1.0-SNAPSHOT-jar-with-dependencies.jar", "com.github.charlesknight.HangmanCMD"]
